name: 'Deploy frontend code'

on:
  push:
    branches:
      - "main"
    paths:
      - frontend/app/**
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - "main"
    paths:
      - frontend/app/**

env:
  APP_LOCATION: "frontend/app"
  APP_BUILD_COMMAND: "npm run generate"
  OUTPUT_LOCATION: "dist"

permissions:
  contents: read

jobs:
  build_and_deploy_staging:
    name: "[staging] Build and Deploy"

    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')

    environment:
      name: staging
      url: https://orange-sand-0e6b75700.1.azurestaticapps.net

    runs-on: ubuntu-latest

    permissions:
      contents: read # for actions/checkout to fetch code
      pull-requests: write # for Azure/static-web-apps-deploy to comment on PRs

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} # secret containing api token for app
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: ${{ env.APP_LOCATION }}
          app_build_command: ${{ env.APP_BUILD_COMMAND }}
          output_location: ${{ env.OUTPUT_LOCATION }}
          ###### End of Repository/Build Configurations ######

  close_pull_request_staging:
    name: "[staging] Close Pull Request"
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    environment: staging
    runs-on: ubuntu-latest
    permissions:
      contents: none
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} # secret containing api token for app
          action: "close"

  build_and_deploy_prod:
    name: "[prod] Build and Deploy"

    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    environment:
      name: production
      url: https://salmon-plant-0c0e13700.1.azurestaticapps.net

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          app_build_command: ${{ env.APP_BUILD_COMMAND }}
          output_location: ${{ env.OUTPUT_LOCATION }}
