name: Deploy backend code

on:
  push:
    branches:
      - "main"
    paths:
      - "backend/api/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "backend/api/**"
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: backend/api
  NODE_VERSION: 16
  ARTIFACT_NAME: backend-api

jobs:
  build:
    name: "Build"

    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build
        run: |
          npm ci
          npm run build --if-present

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

  deploy_staging:
    name: "[staging] Deploy"
    needs: build

    if: github.event_name == 'pull_request'

    environment:
      name: staging
      url: https://orange-sand-0e6b75700.1.azurestaticapps.net

    runs-on: windows-latest

    env:
      AZURE_FUNCITONAPP_NAME: rg-msgh-devops-demo-staging

    defaults:
      run:
        shell: pwsh
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
          
      - name: Deploy
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCITONAPP_NAME }}
          package: .
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

  build_production:
    name: "[prod] Build"
    needs: build

    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    environment:
      name: production
      url: https://salmon-plant-0c0e13700.1.azurestaticapps.net

    runs-on: windows-latest

    env:
      AZURE_FUNCITONAPP_NAME: func-msgh-devops-demo-prod-backend

    defaults:
      run:
        shell: pwsh
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
          
      - name: Deploy
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCITONAPP_NAME }}
          package: .
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
