name: 'prod: Update cloud resources'

on:
  push:
    branches:
      - "main"
    paths:
      - "iac/terraform/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "iac/terraform/**"
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  TERRAFORM_BACKEND_STORAGE_ACCOUNT_NAME: stprp6rlhavin2g
  WORKLOAD_NAME: msgh-devops-demo

defaults:
  run:
    working-directory: iac/terraform/envs/prod

jobs:
  check:
    name: 'Check updates'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init -backend-config="resource_group_name=${RESOURCE_GROUP_MANAGE_NAME}" -backend-config="storage_account_name=${TERRAFORM_BACKEND_STORAGE_ACCOUNT_NAME}"
      env:
        RESOURCE_GROUP_MANAGE_NAME: rg-${{ env.WORKLOAD_NAME }}-manage

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false
      env:
        TF_VAR_workload_name: ${{ env.WORKLOAD_NAME }}

  deploy:
    name: 'Deploy resources'
    needs: check

    if: (github.ref == 'refs/heads/main' && github.event_name == 'push') || github.event_name == 'workflow_dispatch'

    environment:
      name: production
      url: https://salmon-plant-0c0e13700.1.azurestaticapps.net

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init -backend-config="resource_group_name=${RESOURCE_GROUP_MANAGE_NAME}" -backend-config="storage_account_name=${TERRAFORM_BACKEND_STORAGE_ACCOUNT_NAME}"
      env:
        RESOURCE_GROUP_MANAGE_NAME: rg-${{ env.WORKLOAD_NAME }}-manage

    - name: Terraform Plan
      run: terraform plan -input=false
      env:
        TF_VAR_workload_name: ${{ env.WORKLOAD_NAME }}

    # Deploy resources
    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
      env:
        TF_VAR_workload_name: ${{ env.WORKLOAD_NAME }}
